import { Layout } from '@/components/Layout';
import type { Metadata } from 'next';
import { EB_Garamond } from 'next/font/google';

const ebGaramond = EB_Garamond({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning
        className={`${ebGaramond.className} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
